### ISSUE TITLE
threading error

### ISSUE THREAD

**Issue by ischneider** [planetlabs/planet-client-python#13]
While running thumbnails command with single ID

```
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run

  File "/Users/REDACTED/.pex/install/futures-3.0.3-py2-none-any.whl.20b9d64ae605ce774575ed604af7a88f5586d4f7/futures-3.0.3-py2-none-any.whl/concurrent/futures/thread.py", line 65, in _worker

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Queue.py", line 179, in get

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 383, in notify

<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

**Comment by bosth** [comment]
I don't see this either.

**Comment by ischneider** [comment]
Closing for now, reopen if needed
