### ISSUE TITLE
502 Bad Gateway 

### ISSUE THREAD

**Issue by tuanakka0101** [planetlabs/planet-client-python#141]
I had used Planet API Python, but when try to search items it always return 502 Bad gateway.
I change to use requests, no problem.

Traceback (most recent call last):
...
  File "/usr/local/lib/python2.7/dist-packages/planet/api/client.py", line 162, in quick_search
    body_type=models.Items, data=body, method='POST')).get_body()
  File "/usr/local/lib/python2.7/dist-packages/planet/api/models.py", line 45, in get_body
    resp = self._dispatcher._dispatch(self.request)
  File "/usr/local/lib/python2.7/dist-packages/planet/api/dispatch.py", line 155, in _dispatch
    return _do_request(self.session, request)
  File "/usr/local/lib/python2.7/dist-packages/planet/api/dispatch.py", line 125, in _do_request
    check_status(resp)
  File "/usr/local/lib/python2.7/dist-packages/planet/api/utils.py", line 88, in check_status
    raise exceptions.APIException('%s: %s' % (status, response.text))
planet.api.exceptions.APIException: 502: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.1.19</center>
</body>
</html>

**Comment by tuanakka0101** [comment]
Sorry, it is my fault. I use geo filter wrong.
