### ISSUE TITLE
Syntax Error 

### ISSUE THREAD

**Issue by ehtishamkhan** [planetlabs/planet-client-python#144]
Getting a syntax error when planet client. Please advise. 

Traceback (most recent call last):
  File "C:\Users\USZLKZ9\Desktop\machine.learning\python\WPy-3701\python-3.7.0.amd64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\USZLKZ9\Desktop\machine.learning\python\WPy-3701\python-3.7.0.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\USZLKZ9\Desktop\machine.learning\python\WPy-3701\python-3.7.0.amd64\Scripts\planet.exe\__main__.py", line 5, in <module>
  File "C:\Users\USZLKZ9\Desktop\machine.learning\python\WPy-3701\python-3.7.0.amd64\lib\site-packages\planet\scripts\__init__.py", line 15, in <module>
    from planet.scripts import cli
  File "C:\Users\USZLKZ9\Desktop\machine.learning\python\WPy-3701\python-3.7.0.amd64\lib\site-packages\planet\scripts\cli.py", line 19, in <module>
    from planet import api
  File "C:\Users\USZLKZ9\Desktop\machine.learning\python\WPy-3701\python-3.7.0.amd64\lib\site-packages\planet\api\__init__.py", line 18, in <module>
    from .client import (ClientV1)
  File "C:\Users\USZLKZ9\Desktop\machine.learning\python\WPy-3701\python-3.7.0.amd64\lib\site-packages\planet\api\client.py", line 17, in <module>
    from .dispatch import RequestsDispatcher
  File "C:\Users\USZLKZ9\Desktop\machine.learning\python\WPy-3701\python-3.7.0.amd64\lib\site-packages\planet\api\dispatch.py", line 24, in <module>
    from . models import Response
  File "C:\Users\USZLKZ9\Desktop\machine.learning\python\WPy-3701\python-3.7.0.amd64\lib\site-packages\planet\api\models.py", line 58
    def get_body_async(self, handler, await=None):
                                          ^
SyntaxError: invalid syntax

**Comment by sarasafavi** [comment]
Resolved in release 1.2.2
