### ISSUE TITLE
fix bug in orders downloader that may be causing odd behavior

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#233]
We are seeing odd behavior in orders downloader (#221, #222). While working to fix these errors was in progress, a bug was found. The effects of this bug aren't fully known but it may be the root of all of these issues. This is a blind whackamole type of fix but worth a few hours to see if it magically fixes the orders downloads!

In `planet.api.downloader._OrderDownloadStage._do`, `self._results.put` expects three arguments whereas only two arguments are given (https://github.com/planetlabs/planet-client-python/blob/master/planet/api/downloader.py#L515). Adding `None` as the second argument is probably the right approach but then the CLI croaks with another error a little further down the line so more work may be needed.

**Comment by jreiberkyle** [comment]
Made the fixes. Now this exception in stderr correlates to a failure to download a file:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jennifer.kyle/pl/planet-client-python/planet/api/utils.py", line 328, in run
    res.append(f(*a, **kw))
  File "/Users/jennifer.kyle/pl/planet-client-python/planet/api/downloader.py", line 358, in download
    return self._run(items, asset_types, dest)
  File "/Users/jennifer.kyle/pl/planet-client-python/planet/api/downloader.py", line 402, in _run
    body = self._waiting.wait()
  File "/Users/jennifer.kyle/pl/planet-client-python/planet/api/models.py", line 72, in wait
    self._future.result()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jennifer.kyle/.virtualenvs/plclient/lib/python3.8/site-packages/requests_futures/sessions.py", line 74, in wrap
    background_callback(self, resp)
  File "/Users/jennifer.kyle/pl/planet-client-python/planet/api/models.py", line 52, in _async_callback
    check_status(response)
  File "/Users/jennifer.kyle/pl/planet-client-python/planet/api/utils.py", line 90, in check_status
    raise exception(response.text)
planet.api.exceptions.TooManyRequests: max rate reached: retry-in 200ms
```

**Comment by jreiberkyle** [comment]
Turns out this failure is in the asynchronous code that uses `futures`. There doesn't appear to be an easy way to retry with `futures` (https://github.com/ross/requests-futures/issues/26). So what likely needs to happen here is spacing the requests coming from the sessions.

**Comment by jreiberkyle** [comment]
Trying to space the requests is proving difficult. There was already request spacing in `downloader` so I suspected there would need to be more spacing outside of downloader. But the issue appears to be more with `urllib3.connectionpool` starting a new connection. Here is what happens right before `TooManyRequests` is received:

```
2020-10-27 22:40:51,731 - planet.api.downloader - DEBUG - _OrderDownloadStage : sleep for 0.50
109 2020-10-27 22:40:51,832 - urllib3.connectionpool - DEBUG - https://api.planet.com:443 "GET /compute/ops/download/<<blah>>
110 2020-10-27 22:40:51,838 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): link.planet.com:443
111 2020-10-27 22:40:51,974 - urllib3.connectionpool - DEBUG - https://link.planet.com:443 "GET /orders/v2/download/<<blah>>
```

`urllib3.connectionpool` is called by `requests`

**Comment by jreiberkyle** [comment]
Ok, abandoning this effort because the bug is too difficult to track down. Rework in version 2 of the client will likely make this no longer necessary.

**Comment by Shane98c** [comment]
Hi @jreiberkyle, I appreciate you documenting this here because I'm now running into the same issue. Do you have any suggestions for working around it? Is the implementation of order downloads in v2 ready for some external testing that may get around this? Thanks for your work!
