### ISSUE TITLE
httpx / httpcore exception with CLI on V2

### ISSUE THREAD

**Issue by kevinlacaille** [planetlabs/planet-client-python#312]
About 1 in every 10 times I run the CLI with `httpx==0.16.1`, I get:
`httpcore.CloseError: [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2756)`

- `httpx` is somehow, for some reason letting an `httpcore` exception bubble up, which is odd.
- This `httpcore.CloseError` exception line leads us to find these two GitHub issues:
    - https://github.com/encode/httpx/issues/1459 -- looks like we aren't the first people to hit this indeterminate/non-reproachable issue with `httpx` specifically, at least.
    - Looks like the issue with `httpcore` exceptions leaking into `httpx` was also being tracked https://github.com/encode/httpx/issues/1463
- In theory, at least the leaky exception issue was fixed in `httpx 0.17` -- and maybe bumping up to a more recent version could fix this issue. 

After bumping up to `httpx==0.19.0` (set `httpx>=0.17`), every time I run the CLI I get:
`httpx.ResponseNotRead: Attempted to access streaming response content, without having called 'read()'.`

**Idea**: Consider try `httpx==0.17`, where it appears the `httpcore` bug was fixed.

**Comment by kevinlacaille** [comment]
Looks pretty bug-less at `httpx==0.17`. Should be a quick fix in the `setup.py`.

**Comment by kevinlacaille** [comment]
It seems as though `httpx==0.17` is still returning the same `CloseError` exception. A function having issues with this is `aclose` in `models.py` when calling `self.http_response.aclose()`.

**Comment by kevinlacaille** [comment]
This is related to #276, but we'll leave this open as it provides plenty of additional information.

**Comment by kevinlacaille** [comment]
Upgrading to ```httpx==0.18.0``` seems to fix this for me.

**Comment by kevinlacaille** [comment]
I'm still having these issues with `httpx==0.16.1`, as v2 currently stands. Here's how to recreate my issue:

**Create an order:**
```
import asyncio
import os

import planet

iowa_aoi = {
    "type": "Polygon",
    "coordinates": [[
        [-91.198465, 42.893071],
        [-91.121931, 42.893071],
        [-91.121931, 42.946205],
        [-91.198465, 42.946205],
        [-91.198465, 42.893071]]]
}

iowa_images = [
    '20200925_161029_69_2223',
    '20200925_161027_48_2223'
]
iowa_order = planet.order_request.build_request(
    'iowa_order',
    [planet.order_request.product(iowa_images, 'analytic', 'PSScene4Band')],
    tools=[planet.order_request.clip_tool(iowa_aoi)]
)

async def create_and_download(order_detail, directory, client):
    with planet.reporting.StateBar(state='creating') as reporter:
        # create
        order = await client.create_order(order_detail)
        reporter.update(state='created', order_id=order.id)

        # poll
        await client.poll(order.id, report=reporter.update)

    # download
    await client.download_order(order.id, progress_bar=True)

async def main():
    async with planet.Session() as ps:
        client = planet.OrdersClient(ps)

        await asyncio.gather(
            create_and_download(iowa_order, DOWNLOAD_DIR, client),
        )

if __name__ == '__main__':
    asyncio.run(main())
```

**Download the order:**
```planet orders download 1808f885-5a46-4363-bf16-aedb33fb1711```

**The associated traceback:**
```
00:01 - order 1808f885-5a46-4363-bf16-aedb33fb1711 - state: success
Traceback (most recent call last):
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/bin/planet", line 33, in <module>
    sys.exit(load_entry_point('planet', 'console_scripts', 'planet')())
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/scripts/cli.py", line 64, in wrapper
    f(*args, **kwargs)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/scripts/cli.py", line 35, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/scripts/cli.py", line 217, in download
    filenames = await cl.download_order(
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/clients/orders.py", line 339, in download_order
    filenames = [await self.download_asset(location,
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/clients/orders.py", line 339, in <listcomp>
    filenames = [await self.download_asset(location,
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/clients/orders.py", line 308, in download_asset
    dl_filename = await body.write(dl_path,
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/http.py", line 280, in __aexit__
    await self.response.aclose()
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/models.py", line 112, in aclose
    await self.http_response.aclose()
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpx/_models.py", line 1299, in aclose
    await self._on_close(self)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpx/_client.py", line 1513, in on_close
    await stream.aclose()
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 69, in aclose
    await self.stream.aclose()
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_bytestreams.py", line 78, in aclose
    await self._aclose_func()
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_async/http11.py", line 192, in _response_closed
    await self.aclose()
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_async/http11.py", line 202, in aclose
    await self.socket.aclose()
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_backends/asyncio.py", line 198, in aclose
    await self.stream_writer.wait_closed()  # type: ignore
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.CloseError: [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2756)
```

**Current solution:** Upgrade `httpx` to `0.18.0` in setup.py.

**Comment by kevinlacaille** [comment]
While on `httpx==0.18.0` the orders list module breaks, however when switching back to `0.16.1`, the module works as expected.

On `0.18.0`:
```
❯ planet orders list
Traceback (most recent call last):
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/models.py", line 305, in __anext__
    item = self._items.pop(0)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/bin/planet", line 33, in <module>
    sys.exit(load_entry_point('planet', 'console_scripts', 'planet')())
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/scripts/cli.py", line 64, in wrapper
    f(*args, **kwargs)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/scripts/cli.py", line 35, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/scripts/cli.py", line 164, in list
    orders = await cl.list_orders(state=state, limit=limit, as_json=True)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/clients/orders.py", line 444, in list_orders
    ret = [o.json async for o in orders]
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/clients/orders.py", line 444, in <listcomp>
    ret = [o.json async for o in orders]
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/models.py", line 412, in __anext__
    return Order(await super().__anext__())
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/models.py", line 309, in __anext__
    page = await self._pages.__anext__()
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/models.py", line 322, in _get_pages
    resp = await self._do_request(request)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/clients/orders.py", line 119, in _do_request
    return await self._session.request(request)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/http.py", line 204, in request
    return await self._retry(self._request, request, stream=stream)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/http.py", line 175, in _retry
    return await func(*a, **kw)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/http.py", line 208, in _request
    http_resp = await self._client.send(request.http_request,
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpx/_client.py", line 1511, in send
    response = await self._send_handling_auth(
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpx/_client.py", line 1546, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpx/_client.py", line 1580, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpx/_client.py", line 1621, in _send_single_request
    ) = await transport.handle_async_request(
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpx/_transports/default.py", line 277, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 234, in handle_async_request
    response = await connection.handle_async_request(
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_async/connection.py", line 148, in handle_async_request
    return await self.connection.handle_async_request(
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_async/http11.py", line 122, in handle_async_request
    await self._send_request_body(stream, timeout)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_async/http11.py", line 165, in _send_request_body
    async for chunk in stream:
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_bytestreams.py", line 91, in __aiter__
    async for chunk in self._aiterator:
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpx/_content.py", line 75, in __aiter__
    raise StreamClosed()
httpx.StreamClosed: Attempted to read or stream content, but the stream has been closed.```

**Comment by jreiberkyle** [comment]
@kevinlacaille do you think this is related to a timeout error? I was running into some errors with httpx when I was downloading multiple orders async and I was able to fix it by increasing the timeout in the httpx Client. I'm not seeing a Timeout error in the traceback but is this the entire traceback?

**Comment by cholmes** [comment]
Moving this to post-release, as we'll do #279 which likely will mitigate most of the issues. If this does bubble up again before release we should actually tackle it.

**Comment by kevinlacaille** [comment]
@jreiberkyle I haven’t had this issue for quite some time, probably >6mo, but I do assume it was a timeout error. @cholmes, I'm all for moving forward with #279 and pushing it post-release 👍
