### ISSUE TITLE
Attribute error when downloading from the CLI

### ISSUE THREAD

**Issue by kapadia** [planetlabs/planet-client-python#32]
Looking into this right now.

```shell
$ planet download 20150517_181918_0908 --product analytic
Traceback (most recent call last):
  File "/Users/amitkapadia/anaconda/envs/pl/bin/planet", line 9, in <module>
    load_entry_point('planet==0.0.1', 'console_scripts', 'planet')()
  File "/Users/amitkapadia/anaconda/envs/pl/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Users/amitkapadia/anaconda/envs/pl/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Users/amitkapadia/anaconda/envs/pl/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/amitkapadia/anaconda/envs/pl/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/amitkapadia/anaconda/envs/pl/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Users/amitkapadia/pl/planet-client-python/planet/scripts/__init__.py", line 228, in fetch_scene_geotiff
    api.write_to_file(dest))
AttributeError: 'module' object has no attribute 'write_to_file'
```

**Comment by ischneider** [comment]
Thanks @kapadia and apologies - realized we're lacking coverage while refactoring
