### ISSUE TITLE
Issues with error parsing in create_order()

### ISSUE THREAD

**Issue by kevinlacaille** [planetlabs/planet-client-python#324]
On branch v2-polling-output-310, in orders.py, `create_order()` has issues with parsing the JSON's error message. Specifically, a KeyError occurs in the try/except statement (~line 164), when the JSON message gets queried with the keyword "general".
```
msg_json = json.loads(ex.message)
msg = msg_json['general'][0]['message']
```

Below is the code used for the request, poll, and download the order, taken from `docs/guide.md`:
```
import asyncio
from planet import Session
from planet import OrdersClient

# Create an order
from planet import order_request
products = [
    order_request.product(['20170614_113217_3163208_RapidEye-5'],
                          'analytic', 'REOrthoTile')
]

tools = [
    order_request.toar_tool(scale_factor=10000),
    order_request.reproject_tool(projection='WSG84', kernel='cubic'),
    order_request.tile_tool(1232, origin_x=-180, origin_y=-90,
              pixel_size=0.000027056277056,
              name_template='C1232_30_30_{tilex:04d}_{tiley:04d}')
]

# Build request
request = order_request.build_request(
    'test_order', products, tools)

# Polling & Downloading
from planet import reporting

async def create_poll_and_download():
    async with Session() as sess:
        cl = OrdersClient(sess)
        with reporting.StateBar(state='creating') as bar:
            # create order
            order = await cl.create_order(request)
            bar.update(state='created', order_id=order.id)

            # poll
            await cl.poll(order.id, report=bar.update)

        # download
        await cl.download_order(order.id)

asyncio.run(create_poll_and_download())
```

Below is the traceback for the aforementioned error:

```
BadQuery                                  Traceback (most recent call last)
~/code/repos/planet-client-python/planet/clients/orders.py in create_order(self, request)
    159         try:
--> 160             resp = await self._do_request(req)
    161         except exceptions.BadQuery as ex:

~/code/repos/planet-client-python/planet/clients/orders.py in _do_request(self, request)
    117         '''
--> 118         return await self._session.request(request)
    119

~/code/repos/planet-client-python/planet/http.py in request(self, request, stream)
    203         # 1. https://github.com/encode/httpx/issues/984
--> 204         return await self._retry(self._request, request, stream=stream)
    205

~/code/repos/planet-client-python/planet/http.py in _retry(self, func, *a, **kw)
    174             try:
--> 175                 return await func(*a, **kw)
    176             except exceptions.TooManyRequests:

~/code/repos/planet-client-python/planet/http.py in _request(self, request, stream)
    207         '''Submit a request'''
--> 208         http_resp = await self._client.send(request.http_request,
    209                                             stream=stream)

~/.pyenv/versions/3.9.6/envs/planetSDK/lib/python3.9/site-packages/httpx/_client.py in send(self, request, stream, auth, allow_redirects, timeout)
   1421             for hook in self._event_hooks["response"]:
-> 1422                 await hook(response)
   1423         except Exception:

~/code/repos/planet-client-python/planet/http.py in araise_for_status(*args, **kwargs)
    141         async def araise_for_status(*args, **kwargs):
--> 142             return self._raise_for_status(*args, **kwargs)
    143

~/code/repos/planet-client-python/planet/http.py in _raise_for_status(cls, response)
     80
---> 81         raise exception(msg)
     82

BadQuery: {"code":400,"message":"Unable to parse JSON payload. Confirm syntax and schema."}

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~/code/repos/planet-client-python/test_polling.py in <module>
    127         await cl.download_order(order.id)
    128
--> 129 asyncio.run(create_poll_and_download())

/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py in run(main, debug)
     42         if debug is not None:
     43             loop.set_debug(debug)
---> 44         return loop.run_until_complete(main)
     45     finally:
     46         try:

/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py in run_until_complete(self, future)
    640             raise RuntimeError('Event loop stopped before Future completed.')
    641
--> 642         return future.result()
    643
    644     def stop(self):

~/code/repos/planet-client-python/test_polling.py in create_poll_and_download()
    118         with reporting.StateBar(state='creating') as bar:
    119             # create order
--> 120             order = await cl.create_order(request)
    121             bar.update(state='created', order_id=order.id)
    122

~/code/repos/planet-client-python/planet/clients/orders.py in create_order(self, request)
    162             msg_json = json.loads(ex.message)
    163
--> 164             msg = msg_json['general'][0]['message']
    165             try:
    166                 # get first error field

KeyError: 'general'```

**Comment by kevinlacaille** [comment]
Confirming that I'm still getting this exception on `main`. 

Updated code from `docs/guide.md`:
```
import asyncio
from planet import Session
from planet import OrdersClient

from planet import order_request
products = [
    order_request.product(['20170614_113217_3163208_RapidEye-5'],
                        'analytic', 'REOrthoTile')
 ]

tools = [
    order_request.toar_tool(scale_factor=10000),
    order_request.reproject_tool(projection='WSG84', kernel='cubic'),
    order_request.tile_tool(1232, origin_x=-180, origin_y=-90,
            pixel_size=0.000027056277056,
            name_template='C1232_30_30_{tilex:04d}_{tiley:04d}')
 ]

request = order_request.build_request(
    'test_order', products, tools)


# Polling & Downloading
from planet import reporting

async def create_poll_and_download():
    async with Session() as sess:
        cl = OrdersClient(sess)
        with reporting.StateBar(state='creating') as bar:
            # create order
            order = await cl.create_order(request)
            bar.update(state='created', order_id=order['id'])

            # poll
            await cl.poll(order['id'], report=bar.update)

        # download
        await cl.download_order(order['id'])

asyncio.run(create_poll_and_download())
```

Traceback:
```
Exception has occurred: BadQuery       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
{"code":400,"message":"Unable to parse JSON payload. Confirm syntax and schema."}
  File "/Users/kevin.lacaille/code/repos/planet/planet-client-python/planet/http.py", line 75, in _raise_for_status
    raise exception(msg)
  File "/Users/kevin.lacaille/code/repos/planet/planet-client-python/planet/http.py", line 133, in araise_for_status
    return self._raise_for_status(*args, **kwargs)
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/envs/planetSDK/lib/python3.9/site-packages/httpx/_client.py", line 1422, in send
    await hook(response)
  File "/Users/kevin.lacaille/code/repos/planet/planet-client-python/planet/http.py", line 209, in _request
    http_resp = await self._client.send(request.http_request,
  File "/Users/kevin.lacaille/code/repos/planet/planet-client-python/planet/http.py", line 170, in _retry
    resp = await func(*a, **kw)
  File "/Users/kevin.lacaille/code/repos/planet/planet-client-python/planet/http.py", line 205, in request
    return await self._retry(self._request, request, stream=stream)
  File "/Users/kevin.lacaille/code/repos/planet/planet-client-python/planet/clients/orders.py", line 123, in _do_request
    return await self._session.request(request)
  File "/Users/kevin.lacaille/code/repos/planet/planet-client-python/planet/clients/orders.py", line 160, in create_order
    resp = await self._do_request(req)
  File "/Users/kevin.lacaille/code/repos/planet/planet-client-python/planet/does_this_need_ticket.py", line 31, in create_poll_and_download
    order = await cl.create_order(request)
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/kevin.lacaille/code/repos/planet/planet-client-python/planet/does_this_need_ticket.py", line 40, in <module>
    asyncio.run(create_poll_and_download())
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/runpy.py", line 197, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
```

**Comment by kevinlacaille** [comment]
Manually built request:
```
{'name': 'test_order', 'products': [{'item_ids': ['20170614_113217_3163208_RapidEye-5'], 'item_type': 'REOrthoTile', 'product_bundle': 'analytic'}], 'tools': [{'toar': {'scale_factor': 10000}}, {'reproject': {'projection': 'WSG84', 'kernel': 'cubic'}}, {'tile': {'tile_size': 1232, 'origin_x': -180, 'origin_y': -90, 'pixel_size': 2.7056277056e-05, 'name_template': 'C1232_30_30_{tilex:04d}_{tiley:04d}'}}]}
```

Auto built:
```
{'name': 'test_order', 'products': [{'item_ids': ['20170614_113217_3163208_RapidEye-5'], 'item_type': 'REOrthoTile', 'product_bundle': 'analytic'}], 'subscription_id': [{'toar': {'scale_factor': 10000}}, {'reproject': {'projection': 'WSG84', 'kernel': 'cubic'}}, {'tile': {'tile_size': 1232, 'origin_x': -180, 'origin_y': -90, 'pixel_size': 2.7056277056e-05, 'name_template': 'C1232_30_30_{tilex:04d}_{tiley:04d}'}}]}
```

**Issue:** Auto built request has `subscription_id` where `tools` should be.

**Comment by kevinlacaille** [comment]
**Solution:** Be more explicit!
replace:
`request = order_request.build_request(
    'test_order', products, tools)
`

with 
`request = order_request.build_request(
    'test_order', products=products, tools=tools)
`
