### ISSUE TITLE
httpx read timeout on download

### ISSUE THREAD

**Issue by kevinlacaille** [planetlabs/planet-client-python#349]
Occasionally, a download with timeout. 

Here's an example of a traceback where an order, which previously downloaded with no issues, timedout:

```bash
❯ planet orders download e8a3abe0-18fa-4939-8071-d2ef0a8ed3f1
00:05 - order e8a3abe0-18fa-4939-8071-d2ef0a8ed3f1 - state:
Traceback (most recent call last):
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 218, in arequest
    response = await connection.arequest(
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_async/connection.py", line 106, in arequest
    return await self.connection.arequest(method, url, headers, stream, ext)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_async/http11.py", line 72, in arequest
    ) = await self._receive_response(timeout)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_async/http11.py", line 133, in _receive_response
    event = await self._receive_event(timeout)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_async/http11.py", line 172, in _receive_event
    data = await self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_backends/asyncio.py", line 157, in read
    raise
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/bin/planet", line 33, in <module>
    sys.exit(load_entry_point('planet', 'console_scripts', 'planet')())
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/scripts/cli.py", line 64, in wrapper
    f(*args, **kwargs)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/scripts/cli.py", line 35, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/scripts/cli.py", line 216, in download
    await cl.poll(str(order_id), report=bar.update)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/clients/orders.py", line 400, in poll
    order = await self.get_order(order_id)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/clients/orders.py", line 198, in get_order
    resp = await self._do_request(req)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/clients/orders.py", line 119, in _do_request
    return await self._session.request(request)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/http.py", line 204, in request
    return await self._retry(self._request, request, stream=stream)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/http.py", line 175, in _retry
    return await func(*a, **kw)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/http.py", line 208, in _request
    http_resp = await self._client.send(request.http_request,
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpx/_client.py", line 1406, in send
    response = await self._send_handling_auth(
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpx/_client.py", line 1444, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpx/_client.py", line 1476, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ReadTimeout
```

**Comment by cholmes** [comment]
I think this is the one where we said the fix would just be to increase the default time out? Seems like that should be relatively easy to do?

**Comment by jreiberkyle** [comment]
Will be fixed in #279
