### ISSUE TITLE
Reporting breaks when quiet=True

### ISSUE THREAD

**Issue by kevinlacaille** [planetlabs/planet-client-python#352]
**Summary:** While setting `quiet = True` in the `download()` function in the CLI I get an attribute error with `tqdm_asyncio`.

**Replicate error:**
Add `quiet = True` to line 214 on v2 in cli.py in `download()` so that the function looks like this:
```
async def download(ctx, order_id, quiet, overwrite, dest):
    '''Download order by order ID.'''

    # Download the user's order
    async with orders_client(ctx) as cl:
        quiet = True
        with planet.reporting.StateBar(order_id=order_id,
                                       disable=quiet) as bar:
            await cl.poll(str(order_id), report=bar.update)
            filenames = await cl.download_order(
                    str(order_id),
                    directory=dest,
                    overwrite=overwrite,
                    progress_bar=not quiet)
    click.echo(f'Downloaded {len(filenames)} files.')
```

Then, try and download an order:
```
❯ planet orders download 4acfe01d-6fb9-494f-ae11-ee80ab92d58d
```

Associated traceback:
```
Traceback (most recent call last):
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/bin/planet", line 33, in <module>
    sys.exit(load_entry_point('planet', 'console_scripts', 'planet')())
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kevin.lacaille/.pyenv/versions/planetSDK/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/scripts/cli.py", line 64, in wrapper
    f(*args, **kwargs)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/scripts/cli.py", line 35, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/kevin.lacaille/.pyenv/versions/3.9.6/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/scripts/cli.py", line 217, in download
    await cl.poll(str(order_id), report=bar.update)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/clients/orders.py", line 404, in poll
    report(state=order.state)
  File "/Users/kevin.lacaille/code/repos/planet-client-python/planet/reporting.py", line 95, in update
    self.bar.postfix[1] = self.state
AttributeError: 'tqdm_asyncio' object has no attribute 'postfix'
```

**Comment by kevinlacaille** [comment]
Whoops, I should also mention, that as one might expect, this also breaks the same way when running:
```planet orders download --quiet my-oid```
