### ISSUE TITLE
paged response broken (was: example broken)

### ISSUE THREAD

**Issue by ischneider** [planetlabs/planet-client-python#40]
`python examples/download-tiffs.py`

```python
Traceback (most recent call last):
  File "examples/download-tiffs.py", line 55, in <module>
    for s in scene.iter(pages=3):
  File "planet/api/models.py", line 138, in iter
    page = page.next()
  File "planet/api/models.py", line 128, in next
    request = Request(next, body_type=Scenes)
TypeError: __init__() takes at least 3 arguments (3 given)
```

**Comment by ischneider** [comment]
Updated title: this appears to actually be the underlying paged response being broken.
