### ISSUE TITLE
Issues installing planet client (v1)

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#529]
From another channel:

We tried to install the planet-cli from scratch with the [documentation](https://developers.planet.com/planetschool/2022/Apr/25/setting-up-a-python-development-environment/), using
an @planet.com account.

Everything seemed to work as first but when running the command below we received the following error.

 
Command:

`planet mosaics download global_monthly_2021_07_mosaic --bbox=-96.77,27.18,-75.02,36.87`
 

Error:

```
Traceback (most recent call last):
 File "/Users/rafael.bastidas/Documents/Pyenvironments/cli_test/bin/planet", line 8, in <module>
  sys.exit(main())
 File "/Users/rafael.bastidas/Documents/Pyenvironments/cli_test/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
  return self.main(*args, **kwargs)
 File "/Users/rafael.bastidas/Documents/Pyenvironments/cli_test/lib/python3.9/site-packages/click/core.py", line 1055, in main
  rv = self.invoke(ctx)
 File "/Users/rafael.bastidas/Documents/Pyenvironments/cli_test/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/Users/rafael.bastidas/Documents/Pyenvironments/cli_test/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/Users/rafael.bastidas/Documents/Pyenvironments/cli_test/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
  return ctx.invoke(self.callback, **ctx.params)
 File "/Users/rafael.bastidas/Documents/Pyenvironments/cli_test/lib/python3.9/site-packages/click/core.py", line 760, in invoke
  return __callback(*args, **kwargs)
 File "/Users/rafael.bastidas/Documents/Pyenvironments/cli_test/lib/python3.9/site-packages/planet/scripts/v1.py", line 349, in download_quads
  output.start()
 File "/Users/rafael.bastidas/Documents/Pyenvironments/cli_test/lib/python3.9/site-packages/planet/scripts/util.py", line 298, in start
  _BaseOutput.start(self)
 File "/Users/rafael.bastidas/Documents/Pyenvironments/cli_test/lib/python3.9/site-packages/planet/scripts/util.py", line 264, in start
  self._run()
 File "/Users/rafael.bastidas/Documents/Pyenvironments/cli_test/lib/python3.9/site-packages/planet/scripts/util.py", line 258, in _run
  self._output(self._dl.stats())
 File "/Users/rafael.bastidas/Documents/Pyenvironments/cli_test/lib/python3.9/site-packages/planet/scripts/util.py", line 308, in _output
  self._do_output()
 File "/Users/rafael.bastidas/Documents/Pyenvironments/cli_test/lib/python3.9/site-packages/planet/scripts/util.py", line 317, in _do_output
  width, height = click.termui.get_terminal_size()
AttributeError: module 'click.termui' has no attribute 'get_terminal_siz 
```

It seems like and issue with our dependency "[click](https://pypi.org/project/click/)". When installing with the documentation the newest "click 8.1.2" is installed. 

 

This was checked this with the command "python3 -m pip list":

```
Package      Version
------------------ ---------
certifi      2021.10.8
charset-normalizer 2.0.12
click       8.1.2
idna        3.3
jq         1.2.2
pip        21.1.1
planet       1.4.9
requests      2.27.1
requests-futures  0.9.7
retrying      1.3.3
setuptools     56.0.0
six        1.16.0
urllib3      1.26.9 
 ```

After manually downgrading to an older click version with the following command the non-functioning command from before is working again.

`pip install click==8.0.4`
 

Two people were able to reproduce the issue on our Mac's.

Maybe something broke with the newest click version.

Steps to reproduce:

* (optional) Create a virtual environment with python3 -m venv /path/to/new/virtual/environment"
* (optional) Switch to (exiting or newly created) virtual environment with "source /path/to/new/virtual/environment/bin/activate"
* Run the following: 
```
$ pip install requests
$ pip install retrying
$ pip install jq
$ pip install planet
$ planet init
$ planet mosaics download global_monthly_2021_07_mosaic --bbox=-96.77,27.18,-75.02,36.87
```

**Comment by cholmes** [comment]
I successfully reproduced, looks like the same as https://github.com/nexB/scancode-toolkit/issues/2904#issuecomment-1084593266 - click just decided to drop get_terminal_size in a point release.
