### ISSUE TITLE
Errors on large quick search requests

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#566]
I've been testing out how the v2 cli handles super large quick search requests, putting the limit very high. 

Often it does quite well, I've gotten 200+ megabytes of JSON, which is a good bit more than my best run with v1. But would be great if it could go higher. The error I'm seeing is:

```
planet data search-quick SkySatCollect filter.json --limit 1000000 > skysat3.geojson
Traceback (most recent call last):
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/httpx/_models.py", line 1286, in aiter_raw
    async for part in self.stream:
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 61, in __aiter__
    async for chunk in self.stream:
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/httpcore/_bytestreams.py", line 73, in __aiter__
    async for chunk in self._aiterator:
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/httpcore/_async/http11.py", line 155, in _receive_response_data
    event = await self._receive_event(timeout)
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/httpcore/_async/http11.py", line 169, in _receive_event
    event = self.h11_state.next_event()
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/bin/planet", line 33, in <module>
    sys.exit(load_entry_point('planet', 'console_scripts', 'planet')())
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/cholmes/Repos/planet-client-python/planet/cli/cmds.py", line 57, in wrapper
    func(*args, **kwargs)
  File "/Users/cholmes/Repos/planet-client-python/planet/cli/cmds.py", line 36, in wrapper
    return asyncio.run(func(*args, **kwargs))
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/cholmes/Repos/planet-client-python/planet/cli/data.py", line 108, in search_quick
    async for item in items:
  File "/Users/cholmes/Repos/planet-client-python/planet/models.py", line 320, in __anext__
    page = await self._pages.__anext__()
  File "/Users/cholmes/Repos/planet-client-python/planet/models.py", line 340, in _get_pages
    resp = await self._do_request(request)
  File "/Users/cholmes/Repos/planet-client-python/planet/clients/data.py", line 86, in _do_request
    return await self._session.request(request)
  File "/Users/cholmes/Repos/planet-client-python/planet/http.py", line 230, in request
    return await self._retry(self._request, request, stream=stream)
  File "/Users/cholmes/Repos/planet-client-python/planet/http.py", line 174, in _retry
    resp = await func(*a, **kw)
  File "/Users/cholmes/Repos/planet-client-python/planet/http.py", line 234, in _request
    http_resp = await self._client.send(request.http_request,
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/httpx/_client.py", line 1416, in send
    await response.aread()
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/httpx/_models.py", line 1234, in aread
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/httpx/_models.py", line 1234, in <listcomp>
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/httpx/_models.py", line 1247, in aiter_bytes
    async for chunk in self.aiter_raw():
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/httpx/_models.py", line 1288, in aiter_raw
    yield part
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/cholmes/Repos/venvs/planet-v2-cli/lib/python3.9/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
```

**Comment by cholmes** [comment]
I've continued to test this, most always get the same error. It can happen with anywhere from like 10,000 results, or less. The most I've gotten was ~220,000. Seems to often be around 100k.

**Comment by cholmes** [comment]
Likely related to #578

**Comment by cholmes** [comment]
Tested #640 and it solves all the issues I've had. So close this one when that lands.

**Comment by jreiberkyle** [comment]
landed!
