### ISSUE TITLE
Trouble with submitting my first order

### ISSUE THREAD

**Issue by Deadpeng** [planetlabs/planet-client-python#649]
Hi all,

I am new to the Python API for Planet and have just received an API key.

I tried to test out Planet with the following example on github: [orders_create_and_download_multiple_orders.py](https://github.com/planetlabs/planet-client-python/blob/main/examples/orders_create_and_download_multiple_orders.py)

by copying and pasting the code directly into Python but I instead receive:

Traceback (most recent call last):
  File "C:\Users\PengPengZheng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\planet\auth.py", line 91, in from_env
    auth = APIKeyAuth(api_key)
  File "C:\Users\PengPengZheng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\planet\auth.py", line 208, in __init__
    raise APIKeyAuthException('API key cannot be empty.')
planet.auth.APIKeyAuthException: API key cannot be empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PengPengZheng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\planet\http.py", line 129, in __init__
    auth = Auth.from_env()
  File "C:\Users\PengPengZheng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\planet\auth.py", line 94, in from_env
    raise AuthException(
planet.exceptions.AuthException: Environment variable PL_API_KEY either does not exist or is empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PengPengZheng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\planet\auth.py", line 69, in from_file
    secrets = _SecretFile(filename).read()
  File "C:\Users\PengPengZheng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\planet\auth.py", line 248, in read
    with open(self.path, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PengPengZheng\\.planet.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PengPengZheng\Documents\Highlightplot\tester.py", line 67, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\PengPengZheng\Documents\Highlightplot\tester.py", line 57, in main
    async with planet.Session() as ps:
  File "C:\Users\PengPengZheng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\planet\http.py", line 131, in __init__
    auth = Auth.from_file()
  File "C:\Users\PengPengZheng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\planet\auth.py", line 72, in from_file
    raise AuthException(f'File {filename} does not exist.')
planet.exceptions.AuthException: File C:\Users\PengPengZheng\.planet.json does not exist.
[Finished in 0.328s]
 How do I fix this?

**Comment by jreiberkyle** [comment]
It looks like you haven't initialized the sdk. Check out the [Quick Start](https://github.com/planetlabs/planet-client-python#quick-start)
